package org.seasar.doma.jdbc.command;

import static org.seasar.doma.internal.util.AssertionUtil.assertNotNull;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import org.seasar.doma.internal.jdbc.command.PreparedSqlParameterBinder;
import org.seasar.doma.internal.jdbc.util.JdbcUtil;
import org.seasar.doma.jdbc.OptimisticLockException;
import org.seasar.doma.jdbc.PreparedSql;
import org.seasar.doma.jdbc.SqlExecutionException;
import org.seasar.doma.jdbc.UniqueConstraintException;
import org.seasar.doma.jdbc.query.ModifyQuery;

/**
 * An abstract class for commands that modify database data.
 *
 * @param <QUERY> the query type
 */
public abstract class ModifyCommand<QUERY extends ModifyQuery> implements Command<Integer> {

  protected final QUERY query;

  protected final PreparedSql sql;

  protected ModifyCommand(QUERY query) {
    assertNotNull(query);
    this.query = query;
    this.sql = query.getSql();
  }

  @Override
  public Integer execute() {
    if (!query.isExecutable()) {
      var logger = query.getConfig().getJdbcLogger();
      logger.logSqlExecutionSkipping(
          query.getClassName(), query.getMethodName(), query.getSqlExecutionSkipCause());
      return 0;
    }
    var connection = JdbcUtil.getConnection(query.getConfig().getDataSource());
    try {
      var preparedStatement = prepareStatement(connection);
      try {
        log();
        setupOptions(preparedStatement);
        bindParameters(preparedStatement);
        return executeInternal(preparedStatement);
      } catch (SQLException e) {
        var dialect = query.getConfig().getDialect();
        throw new SqlExecutionException(
            query.getConfig().getExceptionSqlLogType(), sql, e, dialect.getRootCause(e));
      } finally {
        JdbcUtil.close(preparedStatement, query.getConfig().getJdbcLogger());
      }
    } finally {
      JdbcUtil.close(connection, query.getConfig().getJdbcLogger());
    }
  }

  protected PreparedStatement prepareStatement(Connection connection) {
    if (query.isAutoGeneratedKeysSupported()) {
      var config = query.getConfig();
      var dialect = config.getDialect();
      switch (dialect.getAutoGeneratedKeysType()) {
        case FIRST_COLUMN:
          return JdbcUtil.prepareStatementForAutoGeneratedKeysOfFirstColumn(connection, sql);
        case DEFAULT:
          return JdbcUtil.prepareStatementForAutoGeneratedKeys(connection, sql);
      }
    }
    return JdbcUtil.prepareStatement(connection, sql);
  }

  protected abstract int executeInternal(PreparedStatement preparedStatement) throws SQLException;

  protected void log() {
    var logger = query.getConfig().getJdbcLogger();
    logger.logSql(query.getClassName(), query.getMethodName(), sql);
  }

  protected void setupOptions(PreparedStatement preparedStatement) throws SQLException {
    if (query.getQueryTimeout() > 0) {
      preparedStatement.setQueryTimeout(query.getQueryTimeout());
    }
  }

  protected void bindParameters(PreparedStatement preparedStatement) throws SQLException {
    var binder = new PreparedSqlParameterBinder(query);
    binder.bind(preparedStatement, sql.getParameters());
  }

  protected int executeUpdate(PreparedStatement preparedStatement) throws SQLException {
    try {
      var updatedRows = preparedStatement.executeUpdate();
      validateRows(updatedRows);
      return updatedRows;
    } catch (SQLException e) {
      var dialect = query.getConfig().getDialect();
      if (dialect.isUniqueConstraintViolated(e)) {
        throw new UniqueConstraintException(query.getConfig().getExceptionSqlLogType(), sql, e);
      }
      throw e;
    }
  }

  protected void validateRows(int rows) {
    if (query.isOptimisticLockCheckRequired() && rows == 0) {
      throw new OptimisticLockException(query.getConfig().getExceptionSqlLogType(), sql);
    }
  }
}
