name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'New Features'
    labels:
      - 'feat'
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Maintenance'
    labels:
      - 'ci'
      - 'chore'
      - 'perf'
      - 'refactor'
      - 'security'
      - 'test'
  - title: 'Documentation'
    label: 'docs'
  - title: 'Dependency Upgrades'
    label: 'dependencies'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feat'
      - 'feature'
  patch:
    labels:
      - 'patch'
  default: patch
