/*
 * Copyright 2004-2010 the Seasar Foundation and the Others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package org.seasar.doma.jdbc.query;

import static org.seasar.doma.internal.util.AssertionUtil.assertEquals;
import static org.seasar.doma.internal.util.AssertionUtil.assertNotNull;

import java.lang.reflect.Method;
import java.sql.Statement;
import java.util.ArrayList;

import org.seasar.doma.internal.jdbc.entity.AbstractPostInsertContext;
import org.seasar.doma.internal.jdbc.entity.AbstractPreInsertContext;
import org.seasar.doma.internal.jdbc.sql.PreparedSql;
import org.seasar.doma.internal.jdbc.sql.PreparedSqlBuilder;
import org.seasar.doma.jdbc.Config;
import org.seasar.doma.jdbc.JdbcException;
import org.seasar.doma.jdbc.SqlKind;
import org.seasar.doma.jdbc.dialect.Dialect;
import org.seasar.doma.jdbc.entity.EntityPropertyType;
import org.seasar.doma.jdbc.entity.EntityType;
import org.seasar.doma.jdbc.entity.GeneratedIdPropertyType;
import org.seasar.doma.jdbc.entity.Property;
import org.seasar.doma.jdbc.id.IdGenerationConfig;
import org.seasar.doma.message.Message;

/**
 * @author taedium
 * 
 */
public class AutoBatchInsertQuery<ENTITY> extends AutoBatchModifyQuery<ENTITY> implements
        BatchInsertQuery {

    protected GeneratedIdPropertyType<? super ENTITY, ENTITY, ?, ?> generatedIdPropertyType;

    protected IdGenerationConfig idGenerationConfig;

    protected boolean batchSupported = true;

    public AutoBatchInsertQuery(EntityType<ENTITY> entityType) {
        super(entityType);
    }

    @Override
    public void prepare() {
        assertNotNull(method, config, callerClassName, callerMethodName,
                entities, sqls);
        int size = entities.size();
        if (size == 0) {
            return;
        }
        executable = true;
        executionSkipCause = null;
        currentEntity = entities.get(0);
        preInsert();
        prepareIdAndVersionPropertyTypes();
        prepareOptions();
        prepareTargetPropertyTypes();
        prepareIdValue();
        prepareVersionValue();
        prepareSql();
        entities.set(0, currentEntity);
        for (int i = 1; i < size; i++) {
            currentEntity = entities.get(i);
            preInsert();
            prepareIdValue();
            prepareVersionValue();
            prepareSql();
            entities.set(i, currentEntity);
        }
        currentEntity = null;
        assertEquals(entities.size(), sqls.size());
    }

    protected void preInsert() {
        AutoBatchPreInsertContext<ENTITY> context = new AutoBatchPreInsertContext<ENTITY>(
                entityType, method, config);
        entityType.preInsert(currentEntity, context);
        if (context.getNewEntity() != null) {
            currentEntity = context.getNewEntity();
        }
    }

    @Override
    protected void prepareIdAndVersionPropertyTypes() {
        super.prepareIdAndVersionPropertyTypes();
        generatedIdPropertyType = entityType.getGeneratedIdPropertyType();
        if (generatedIdPropertyType != null) {
            if (idGenerationConfig == null) {
                idGenerationConfig = new IdGenerationConfig(config, entityType);
                generatedIdPropertyType
                        .validateGenerationStrategy(idGenerationConfig);
                autoGeneratedKeysSupported = generatedIdPropertyType
                        .isAutoGeneratedKeysSupported(idGenerationConfig);
                batchSupported = generatedIdPropertyType
                        .isBatchSupported(idGenerationConfig);
            }
        }
    }

    protected void prepareTargetPropertyTypes() {
        targetPropertyTypes = new ArrayList<>(entityType
                .getEntityPropertyTypes().size());
        for (EntityPropertyType<ENTITY, ?> propertyType : entityType
                .getEntityPropertyTypes()) {
            if (!propertyType.isInsertable()) {
                continue;
            }
            if (propertyType.isId()) {
                if (propertyType != generatedIdPropertyType
                        || generatedIdPropertyType
                                .isIncluded(idGenerationConfig)) {
                    targetPropertyTypes.add(propertyType);
                }
                if (generatedIdPropertyType == null) {
                    Property<ENTITY, ?> property = propertyType.createProperty();
                    property.load(currentEntity);
                    if (property.getWrapper().get() == null) {
                        throw new JdbcException(Message.DOMA2020,
                                entityType.getName(), propertyType.getName());
                    }
                }
                continue;
            }
            if (!isTargetPropertyName(propertyType.getName())) {
                continue;
            }
            targetPropertyTypes.add(propertyType);
        }
    }

    protected void prepareIdValue() {
        if (generatedIdPropertyType != null && idGenerationConfig != null) {
            ENTITY newEntity = generatedIdPropertyType.preInsert(entityType,
                    currentEntity, idGenerationConfig);
            currentEntity = newEntity;
        }
    }

    protected void prepareVersionValue() {
        if (versionPropertyType != null) {
            currentEntity = versionPropertyType.setIfNecessary(entityType,
                    currentEntity, 1);
        }
    }

    protected void prepareSql() {
        Dialect dialect = config.getDialect();
        PreparedSqlBuilder builder = new PreparedSqlBuilder(config,
                SqlKind.BATCH_INSERT);
        builder.appendSql("insert into ");
        builder.appendSql(entityType.getQualifiedTableName(dialect::applyQuote));
        builder.appendSql(" (");
        for (EntityPropertyType<ENTITY, ?> p : targetPropertyTypes) {
            builder.appendSql(p.getColumnName(dialect::applyQuote));
            builder.appendSql(", ");
        }
        builder.cutBackSql(2);
        builder.appendSql(") values (");
        for (EntityPropertyType<ENTITY, ?> propertyType : targetPropertyTypes) {
            Property<ENTITY, ?> property = propertyType.createProperty();
            property.load(currentEntity);
            builder.appendParameter(property);
            builder.appendSql(", ");
        }
        builder.cutBackSql(2);
        builder.appendSql(")");
        PreparedSql sql = builder.build();
        sqls.add(sql);
    }

    @Override
    public boolean isBatchSupported() {
        return batchSupported;
    }

    @Override
    public void generateId(Statement statement, int index) {
        if (generatedIdPropertyType != null && idGenerationConfig != null) {
            ENTITY newEntity = generatedIdPropertyType.postInsert(entityType,
                    entities.get(index), idGenerationConfig, statement);
            entities.set(index, newEntity);
        }
    }

    @Override
    public void complete() {
        for (int i = 0, len = entities.size(); i < len; i++) {
            currentEntity = entities.get(i);
            postInsert();
            entities.set(i, currentEntity);
        }
    }

    protected void postInsert() {
        AutoBatchPostInsertContext<ENTITY> context = new AutoBatchPostInsertContext<ENTITY>(
                entityType, method, config);
        entityType.postInsert(currentEntity, context);
        if (context.getNewEntity() != null) {
            currentEntity = context.getNewEntity();
        }
    }

    protected static class AutoBatchPreInsertContext<E> extends
            AbstractPreInsertContext<E> {

        public AutoBatchPreInsertContext(EntityType<E> entityType,
                Method method, Config config) {
            super(entityType, method, config);
        }
    }

    protected static class AutoBatchPostInsertContext<E> extends
            AbstractPostInsertContext<E> {

        public AutoBatchPostInsertContext(EntityType<E> entityType,
                Method method, Config config) {
            super(entityType, method, config);
        }
    }
}
