DROP TABLE EMPLOYEE;
DROP TABLE ADDRESS;
DROP TABLE DEPARTMENT;

DROP TABLE COMP_KEY_EMPLOYEE;
DROP TABLE COMP_KEY_ADDRESS;
DROP TABLE COMP_KEY_DEPARTMENT;

DROP TABLE CONSTRAINT_CHECKING;
DROP TABLE LARGE_OBJECT;
DROP TABLE TENSE;
DROP TABLE JOB;
DROP TABLE AUTHORITY;
DROP TABLE NO_ID;
DROP TABLE OWNER_OF_NO_ID;
DROP TABLE PATTERN;

DROP TABLE ID_GENERATOR;
DROP TABLE MY_ID_GENERATOR;
DROP TABLE AUTO_STRATEGY;
DROP TABLE IDENTITY_STRATEGY;
DROP TABLE SEQUENCE_STRATEGY;
DROP TABLE SEQUENCE_STRATEGY2;
DROP TABLE TABLE_STRATEGY;
DROP TABLE TABLE_STRATEGY2;

DROP SEQUENCE SEQUENCE_STRATEGY_ID;
DROP SEQUENCE MY_SEQUENCE_STRATEGY_ID;
