package org.seasar.doma.jdbc.query;

import java.util.List;

import org.seasar.doma.jdbc.PreparedSql;
import org.seasar.doma.jdbc.SqlExecutionSkipCause;
import org.seasar.doma.jdbc.SqlLogType;

/**
 * An object used for building a batch of SQL statements that modify database
 * data.
 */
public interface BatchModifyQuery extends Query {

    List<PreparedSql> getSqls();

    @Override
    PreparedSql getSql();

    boolean isOptimisticLockCheckRequired();

    boolean isAutoGeneratedKeysSupported();

    boolean isExecutable();

    SqlExecutionSkipCause getSqlExecutionSkipCause();

    int getBatchSize();

    SqlLogType getSqlLogType();
}
