/*
 * Copyright 2004-2009 the Seasar Foundation and the Others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package org.seasar.doma.internal.jdbc.query;

import static org.seasar.doma.internal.util.AssertionUtil.*;

import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import org.seasar.doma.internal.jdbc.sql.PreparedSql;
import org.seasar.doma.internal.jdbc.sql.PreparedSqlBuilder;
import org.seasar.doma.jdbc.JdbcException;
import org.seasar.doma.jdbc.entity.EntityMeta;
import org.seasar.doma.jdbc.entity.EntityMetaFactory;
import org.seasar.doma.jdbc.entity.GeneratedIdPropertyMeta;
import org.seasar.doma.jdbc.entity.EntityPropertyMeta;
import org.seasar.doma.jdbc.id.IdGenerationConfig;
import org.seasar.doma.message.DomaMessageCode;

/**
 * @author taedium
 * 
 */
public class AutoBatchInsertQuery<E> extends AutoBatchModifyQuery<E> implements
        BatchInsertQuery {

    protected GeneratedIdPropertyMeta<?> generatedIdProperty;

    protected final List<GeneratedIdPropertyMeta<?>> generatedIdProperties = new ArrayList<GeneratedIdPropertyMeta<?>>();

    protected IdGenerationConfig idGenerationConfig;

    protected boolean batchSupported = true;

    public AutoBatchInsertQuery(EntityMetaFactory<E> entityMetaFactory) {
        super(entityMetaFactory);
    }

    public void prepare() {
        assertNotNull(config);
        Iterator<EntityMeta<E>> it = entityMetas.iterator();
        if (it.hasNext()) {
            executable = true;
            executionSkipCause = null;
            entityMeta = it.next();
            entityMeta.preInsert();
            prepareTableAndColumnNames();
            prepareIdAndVersionProperties();
            prepareOptions();
            prepareTargetProperties();
            prepareVersionValue();
            prepareSql();
        } else {
            return;
        }
        while (it.hasNext()) {
            idProperties.clear();
            generatedIdProperty = null;
            versionProperty = null;
            targetProperties.clear();
            this.entityMeta = it.next();
            entityMeta.preInsert();
            prepareIdAndVersionProperties();
            prepareTargetProperties();
            prepareVersionValue();
            prepareSql();
        }
        assertEquals(entityMetas.size(), sqls.size());
    }

    @Override
    protected void prepareIdAndVersionProperties() {
        super.prepareIdAndVersionProperties();
        generatedIdProperty = entityMeta.getGeneratedIdProperty();
        generatedIdProperties.add(generatedIdProperty);
        if (generatedIdProperty != null) {
            if (idGenerationConfig == null) {
                String idColumnName = columnNameMap.get(generatedIdProperty
                        .getName());
                idGenerationConfig = new IdGenerationConfig(config, entityMeta,
                        tableName, idColumnName);
                generatedIdProperty
                        .validateGenerationStrategy(idGenerationConfig);
                autoGeneratedKeysSupported = generatedIdProperty
                        .isAutoGeneratedKeysSupported(idGenerationConfig);
                batchSupported = generatedIdProperty
                        .isBatchSupported(idGenerationConfig);
            }
            generatedIdProperty.preInsert(idGenerationConfig);
        }
    }

    protected void prepareTargetProperties() {
        for (EntityPropertyMeta<?> p : entityMeta.getPropertyMetas()) {
            if (p.isTransient()) {
                continue;
            }
            if (!p.isInsertable()) {
                continue;
            }
            if (p.isId()) {
                if (p != generatedIdProperty
                        || generatedIdProperty.isIncluded(idGenerationConfig)) {
                    targetProperties.add(p);
                }
                if (generatedIdProperty == null && p.getWrapper().get() == null) {
                    throw new JdbcException(DomaMessageCode.DOMA2020,
                            entityMeta.getName(), p.getName());
                }
                continue;
            }
            if (!isTargetPropertyName(p.getName())) {
                continue;
            }
            targetProperties.add(p);
        }
    }

    protected void prepareVersionValue() {
        if (versionProperty != null) {
            versionProperty.setIfNecessary(1);
        }
    }

    protected void prepareSql() {
        PreparedSqlBuilder builder = new PreparedSqlBuilder(config);
        builder.appendSql("insert into ");
        builder.appendSql(tableName);
        builder.appendSql(" (");
        for (EntityPropertyMeta<?> p : targetProperties) {
            builder.appendSql(columnNameMap.get(p.getName()));
            builder.appendSql(", ");
        }
        builder.cutBackSql(2);
        builder.appendSql(") values (");
        for (EntityPropertyMeta<?> p : targetProperties) {
            builder.appendDomain(p.getWrapper());
            builder.appendSql(", ");
        }
        builder.cutBackSql(2);
        builder.appendSql(")");
        PreparedSql sql = builder.build();
        sqls.add(sql);
    }

    @Override
    public boolean isBatchSupported() {
        return batchSupported;
    }

    @Override
    public void generateId(Statement statement, int index) {
        GeneratedIdPropertyMeta<?> generatedIdProperty = generatedIdProperties
                .get(index);
        generatedIdProperty.postInsert(idGenerationConfig, statement);
    }

}
