/*
 * Copyright 2004-2009 the Seasar Foundation and the Others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package org.seasar.doma.internal.jdbc.query;

import static org.seasar.doma.internal.util.AssertionUtil.*;

import java.sql.Statement;

import org.seasar.doma.internal.jdbc.sql.PreparedSqlBuilder;
import org.seasar.doma.jdbc.JdbcException;
import org.seasar.doma.jdbc.entity.EntityMetaFactory;
import org.seasar.doma.jdbc.entity.GeneratedIdPropertyMeta;
import org.seasar.doma.jdbc.entity.EntityPropertyMeta;
import org.seasar.doma.jdbc.id.IdGenerationConfig;
import org.seasar.doma.message.DomaMessageCode;

/**
 * @author taedium
 * 
 */
public class AutoInsertQuery<E> extends AutoModifyQuery<E> implements
        InsertQuery {

    protected boolean nullExcluded;

    protected GeneratedIdPropertyMeta<?> generatedIdProperty;

    protected IdGenerationConfig idGenerationConfig;

    public AutoInsertQuery(EntityMetaFactory<E> entityMetaFactory) {
        super(entityMetaFactory);
    }

    public void prepare() {
        assertNotNull(config, entityMeta, callerClassName, callerMethodName);
        executable = true;
        entityMeta.preInsert();
        prepareTableAndColumnNames();
        prepareIdAndVersionProperties();
        prepareOptions();
        prepareTargetProperties();
        prepareVersionValue();
        prepareSql();
        assertNotNull(sql);
    }

    @Override
    protected void prepareIdAndVersionProperties() {
        super.prepareIdAndVersionProperties();
        generatedIdProperty = entityMeta.getGeneratedIdProperty();
        if (generatedIdProperty != null) {
            String idColumnName = columnNameMap.get(generatedIdProperty
                    .getName());
            idGenerationConfig = new IdGenerationConfig(config, entityMeta,
                    tableName, idColumnName);
            generatedIdProperty.validateGenerationStrategy(idGenerationConfig);
            autoGeneratedKeysSupported = generatedIdProperty
                    .isAutoGeneratedKeysSupported(idGenerationConfig);
            generatedIdProperty.preInsert(idGenerationConfig);
        }
        versionProperty = entityMeta.getVersionProperty();
    }

    protected void prepareTargetProperties() {
        for (EntityPropertyMeta<?> p : entityMeta.getPropertyMetas()) {
            if (p.isTransient()) {
                continue;
            }
            if (!p.isInsertable()) {
                continue;
            }
            if (p.isId()) {
                if (p != generatedIdProperty
                        || generatedIdProperty.isIncluded(idGenerationConfig)) {
                    targetProperties.add(p);
                }
                if (generatedIdProperty == null && p.getWrapper().get() == null) {
                    throw new JdbcException(DomaMessageCode.DOMA2020,
                            entityMeta.getName(), p.getName());
                }
                continue;
            }
            if (p.isVersion()) {
                targetProperties.add(p);
                continue;
            }
            if (nullExcluded && p.getWrapper().get() == null) {
                continue;
            }
            if (!isTargetPropertyName(p.getName())) {
                continue;
            }
            targetProperties.add(p);
        }
    }

    protected void prepareVersionValue() {
        if (versionProperty != null) {
            versionProperty.setIfNecessary(1);
        }
    }

    protected void prepareSql() {
        PreparedSqlBuilder builder = new PreparedSqlBuilder(config);
        builder.appendSql("insert into ");
        builder.appendSql(tableName);
        builder.appendSql(" (");
        for (EntityPropertyMeta<?> p : targetProperties) {
            builder.appendSql(columnNameMap.get(p.getName()));
            builder.appendSql(", ");
        }
        builder.cutBackSql(2);
        builder.appendSql(") values (");
        for (EntityPropertyMeta<?> p : targetProperties) {
            builder.appendDomain(p.getWrapper());
            builder.appendSql(", ");
        }
        builder.cutBackSql(2);
        builder.appendSql(")");
        sql = builder.build();
    }

    @Override
    public void generateId(Statement statement) {
        if (generatedIdProperty != null) {
            generatedIdProperty.postInsert(idGenerationConfig, statement);
        }
    }

    public void setNullExcluded(boolean nullExcluded) {
        this.nullExcluded = nullExcluded;
    }

}
