name: Release Drafter

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0 # v7
